test:
  DATABASE_URL: "postgresql://anastasiataranova@localhost:5432/tms"
  SECRET_KEY: "1"

development:
  DATABASE_URL: "postgresql://anastasiataranova@localhost:5432/tms"
  SECRET_KEY: "1"
  TELEGRAM_BOT_TOKEN: "1262179828:AAH87YTPClZz3yF1KW5ksXQIsmITgGhnEE8"
  ALLOWED_HOSTS:
    - 5539715ea3bb.ngrok.io
    - 127.0.0.1
    - localhost
  AWS_ACCESS_KEY_ID: "AKIAJD4T6A6QUWMZP5QQ"
  AWS_SECRET_ACCESS_KEY: "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"

docker:
  AWS_ACCESS_KEY_ID: "AKIAJD4T6A6QUWMZP5QQ"
  AWS_SECRET_ACCESS_KEY: "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"
