test:
  DATABASE_URL: "postgresql://anastasiataranova@localhost:5432/weather"
  SECRET_KEY: "1"

development:
  DATABASE_URL: "postgresql://anastasiataranova@localhost:5432/weather"
  SECRET_KEY: "1"
  ALLOWED_HOSTS:
    - 5539715ea3bb.ngrok.io
    - 127.0.0.1
    - localhost
