default:
  ALLOWED_HOSTS: []
  DATABASE_URL: ""
  MODE_CACHING: false
  MODE_DEBUG: false
  MODE_PROFILING: false
  SECRET_KEY: ""
  SENTRY_DSN: ""
  SITE_ID: 0
  TIME_ZONE: ""
  DEBUG: true

development:
  CELERY_BEAT_INVITATION: 30
  MODE_CACHING: 0
  MODE_DEBUG: 1
  MODE_PROFILING: 0
  SECRET_KEY: "1"
  SITE_ID: 1
  TIME_ZONE: "Europe/Minsk"
  DEBUG: true

heroku:
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost
  CELERY_BEAT_INVITATION: 900
  MODE_CACHING: 1
  MODE_DEBUG: 0
  MODE_PROFILING: 0
  DEBUG: true
  DISABLE_COLLECTSTATIC: 1

test:
  EMAIL_FROM: "test@test.name"
  MODE_CACHING: 1
  MODE_DEBUG: 1
  MODE_PROFILING: 0
  SECRET_KEY: "1"
  SITE_ID: 1
  TIME_ZONE: "UTC"
  DEBUG: true