default:
  ALLOWED_HOSTS: []
  AWS_ACCESS_KEY_ID: ""
  AWS_LOCATION: ""
  AWS_S3_REGION_NAME: ""
  AWS_SECRET_ACCESS_KEY: ""
  CELERY_BEAT_INVITATION: -1
  CELERY_BROKER_URL: ""
  DATABASE_URL: ""
  EMAIL_FROM: ""
  EMAIL_HOST: ""
  EMAIL_HOST_PASSWORD: ""
  EMAIL_HOST_USER: ""
  EMAIL_PORT: 0
  EMAIL_USE_SSL: 0
  EMAIL_USE_TLS: 0
  MODE_CACHING: false
  MODE_DEBUG: false
  MODE_PROFILING: false
  SECRET_KEY: ""
  SENTRY_DSN: ""
  SITE_ID: 0
  TIME_ZONE: ""
  DEBUG: true
  TELEGRAM_BOT_TOKEN: ""

development:
  CELERY_BEAT_INVITATION: 30
  MODE_CACHING: 0
  MODE_DEBUG: 1
  MODE_PROFILING: 0
  SECRET_KEY: "1"
  SITE_ID: 1
  TIME_ZONE: "Europe/Minsk"
  DEBUG: true

heroku:
  AWS_LOCATION: "heroku"
  AWS_S3_REGION_NAME: "us-east-1"
  ALLOWED_HOSTS:
    - taranova-travel.herokuapp.com
    - 127.0.0.1
    - localhost
  CELERY_BEAT_INVITATION: 900
  MODE_CACHING: 1
  MODE_DEBUG: 0
  MODE_PROFILING: 0
  DEBUG: true
  DISABLE_COLLECTSTATIC: 1

docker:
  AWS_LOCATION: "docker"
  AWS_S3_REGION_NAME: "us-east-1"
  CELERY_BEAT_INVITATION: 30
  CELERY_BROKER_URL: "redis://taranova-travel-broker"
  DATABASE_URL: "postgresql://anastasiataranova:1@taranova-travel-db:5432/taranova-travel"
  MODE_CACHING: 0
  MODE_DEBUG: 0
  MODE_PROFILING: 0
  SECRET_KEY: "1"
  SITE_ID: 1
  TIME_ZONE: "Europe/Minsk"

travis:
  DATABASE_URL: "postgresql://postgres@localhost:5432/sd"
  DEBUG: true
  SECRET_KEY: "1"
  MODE_CACHING: 1
  MODE_DEBUG: 1
  MODE_PROFILING: 0
  SITE_ID: 1
  TIME_ZONE: "UTC"

test:
  EMAIL_FROM: "test@test.name"
  MODE_CACHING: 1
  MODE_DEBUG: 1
  MODE_PROFILING: 0
  SECRET_KEY: "1"
  SITE_ID: 1
  TIME_ZONE: "UTC"
  DEBUG: true